version: '3.8'

services:
  # MongoDB 資料庫
  mongodb:
    image: mongo:4.4
    container_name: daycare_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: daycare_system
    volumes:
      - mongodb_data:/data/db
    networks:
      - daycare_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 後端 API 服務
  backend:
    build: .
    container_name: daycare_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/daycare_system?authSource=admin
      JWT_SECRET: your_super_secret_jwt_key_here
      JWT_EXPIRE: 7d
      PORT: 5000
      CLIENT_URL: http://localhost:3000
      MOBILE_URL: http://localhost:19006
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - daycare_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 前端 Web 應用
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: daycare_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - daycare_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  daycare_network:
    driver: bridge

